Odiseo\Bundle\EcommerceBundle\Entity\Town:
    type: entity
    table: town
    repositoryClass: Odiseo\Bundle\EcommerceBundle\Repository\TownRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
           column: name
           type: string
           length: 255
    manyToOne:
        region:
            targetEntity: \Odiseo\Bundle\EcommerceBundle\Entity\Region
            joinColumn:
                name: id_region
                referencedColumnName: id
                onUpdate: 'CASCADE'
    lifecycleCallbacks: {  }
