Odiseo\Bundle\OrderBundle\Entity\OrderState:
    type: entity
    table: order_state
    repositoryClass: Odiseo\Bundle\OrderBundle\Repository\OrderStateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
           column: name
           type: string
           length: 255
    oneToOne:
         previousState:
            targetEntity: Odiseo\Bundle\OrderBundle\Entity\OrderState
            joinColumn:
                name: previous_state
                referencedColumnName: id
                onDelete: "CASCADE"
         nextState:
            targetEntity: Odiseo\Bundle\OrderBundle\Entity\OrderState
            joinColumn:
                name: next_state
                referencedColumnName: id
                onDelete: "CASCADE"
    lifecycleCallbacks: {  }
