imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: odiseo.yml }
    - { resource: admin.yml }
    - { resource: '@SyliusCoreBundle/Resources/config/app/main.yml' }

framework:
    translator:      { fallback: '%sylius.locale%' }
    secret:          '%sylius.secret%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: '%kernel.debug%'
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%sylius.locale%"
    trusted_proxies: ~
    session:         ~

twig:
    form:
        resources:
            - SyliusWebBundle:Common:forms.html.twig
            - SyliusResourceBundle::forms.html.twig
            - CmfMediaBundle:Form:fields.html.twig
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    paths:
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Resources/views: PayumCore
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Stripe/Resources/views: PayumStripe

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ 'SyliusWebBundle', 'CmfCreateBundle', 'SyliusResourceBundle', 'OdiseoLokalBuddyBundle', 'OdiseoBackendBundle', 'EasyAdminBundle' ]
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   %sylius.database.driver%
        host:     %sylius.database.host%
        port:     %sylius.database.port%
        dbname:   %sylius.database.name%
        user:     %sylius.database.user%
        password: %sylius.database.password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                dql:
                    string_functions:
                        MATCH: Sylius\Bundle\SearchBundle\Extension\Doctrine\MatchAgainstFunction

doctrine_phpcr:
    session:
        backend: %sylius.phpcr.backend%
        workspace: %sylius.phpcr.workspace%
        username: %sylius.phpcr.user%
        password: %sylius.phpcr.pass%
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

swiftmailer:
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    port:      %sylius.mailer.port%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%
    spool:     { type: memory }

#Sylius configuration
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Odiseo\Bundle\ProductBundle\Entity\Product
            repository: Odiseo\Bundle\ProductBundle\Repository\ProductRepository

sylius_core:
    driver: doctrine/orm
    classes:
        user:
            model: Odiseo\Bundle\UserBundle\Entity\User

sylius_order:
    driver: doctrine/orm
    classes:
        order:
            model: Odiseo\Bundle\OrderBundle\Entity\Order
            repository: Odiseo\Bundle\OrderBundle\Repository\OrderRepository
                        
knp_gaufrette:
    stream_wrapper: ~
                        
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    storage:   gaufrette

    mappings:
        product_images:
            uri_prefix:         /images/product
            upload_destination: %sylius.uploader.filesystem%
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            
liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        product_list:
            filters:
                thumbnail: { size: [800, 533], mode: outbound }
        product_show_header:
            filters:
                thumbnail: { size: [1400, 470], mode: outbound }
        product_gallery_small:
            filters:
                thumbnail: { size: [500, 333], mode: outbound }
        product_gallery_medium:
            filters:
                thumbnail: { size: [1000, 667], mode: outbound }
        product_gallery_large:
            filters:
                thumbnail: { size: [2000, 1333], mode: outbound }
