security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false
                    
        admin:
            switch_user: true
            context:     user
            pattern: /admin.*
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                check_path: /admin/login-check
                failure_path: /admin/login
                default_target_path: /admin/dashboard
                use_forward:  false
                use_referer: true
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: true
            
        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern: ^/.*
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                failure_path: /login
                default_target_path: /
                use_forward:  false
                use_referer: true
            remember_me:
                key: '%sylius.secret%'
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                    amazon:   "/login/check-amazon"
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                    twitter:   "/login/check-twitter"
                login_path:   /login
                failure_path: /login
                oauth_user_provider:
                    service: odiseo.oauth.user_provider
            logout: true
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/media.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/wishlist.*, role: ROLE_USER }
        - { path: "/account.*", role: ROLE_USER }
        - { path: ^/review.*, role: ROLE_USER }
        
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/admin.*", role: ROLE_ADMINISTRATION_ACCESS }
        
        - { path: "/_partial.*", ip: 127.0.0.1 }