# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

imports:
   - { resource: '@OdiseoEcommerceBundle/Resources/config/services.yml' }
   - { resource: '@OdiseoUserBundle/Resources/config/services.yml' }
   - { resource: '@OdiseoProductBundle/Resources/config/services.yml' }
   - { resource: '@OdiseoOrderBundle/Resources/config/services.yml' }
   - { resource: '@OdiseoLokalBuddyBundle/Resources/config/services.yml' }