odiseo_lokalbuddy_frontend_home:
    path:     /
    defaults: { _controller: "OdiseoLokalBuddyBundle:Frontend/Homepage:main" }

odiseo_lokalbuddy_frontend_how_works:
    path:     /how-works
    defaults: { _controller: "OdiseoLokalBuddyBundle:Frontend/HowWorks:main" }

odiseo_product_product:
    resource: "@OdiseoProductBundle/Resources/config/routing/frontend/product.yml"
    prefix:   /experience

odiseo_product_review:
    resource: "@OdiseoProductBundle/Resources/config/routing/frontend/review.yml"
    prefix:   /review

odiseo_ecommerce:
    resource: "@OdiseoEcommerceBundle/Resources/config/routing/main.yml"
    prefix:   /

odiseo_user_account:
    resource: "@OdiseoUserBundle/Resources/config/routing/frontend/account.yml"
    prefix:   /account

odiseo_user_wishlist:
    resource: "@OdiseoUserBundle/Resources/config/routing/frontend/wishlist.yml"
    prefix:   /wishlist
    
#SYLIUS
odiseo_lokalbuddy_backend:
    resource: @SyliusWebBundle/Resources/config/routing/backend/main.yml
    prefix: /admin
    
odiseo_lokalbuddy_frontend:
    resource: "@SyliusWebBundle/Resources/config/routing/frontend/main.yml"
    prefix:   /

sylius_province_choice_form:
    path: /province/choice-form
    defaults:
        _controller: sylius.controller.province:choiceFormAction
        _sylius:
            template: SyliusAddressingBundle:Province:_provinceChoiceForm.html.twig

sylius_partial:
    resource: "@SyliusWebBundle/Resources/config/routing/partial/main.yml"
    prefix: /_partial

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"