odiseo_lokalbuddy_frontend_home:
    path:     /
    defaults: { _controller: "OdiseoLokalBuddyBundle:Frontend/Home:index" }

odiseo_lokalbuddy_frontend_product:
    resource: "@OdiseoProductBundle/Resources/config/routing/frontend/product.yml"
    prefix:   /media

#User Security - Profile - Register
odiseo_lokalbuddy_frontend_user:
    resource: "@OdiseoUserBundle/Resources/config/routing/frontend/user.yml"
    prefix:   /

odiseo_user_profile:
    resource: "@OdiseoUserBundle/Resources/config/routing/frontend/profile.yml"
    prefix:   /profile
    
odiseo_security_frontend:
    resource: "@OdiseoUserBundle/Resources/config/routing/frontend/security.yml"
    prefix:   /
    
fos_user_register_frontend:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

#Imagine    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"