<?php

namespace Odiseo\Bundle\ProductBundle\Repository;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductAssetRepository extends \Doctrine\ORM\EntityRepository
{	
}