<?php

namespace Odiseo\Bundle\ProductBundle\Repository;

/**
 * ProductStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStateRepository extends \Doctrine\ORM\EntityRepository
{
}
