Odiseo\Bundle\UserBundle\Entity\UserProfileTypeFieldValue:
    type: entity
    table: profile_type_field_value
    repositoryClass: Odiseo\Bundle\UserBundle\Repository\UserProfileTypeFieldValueRepository
    id:
        idUser:
            column: id_user
            type: integer
            id: true
        idProfileField:
            column: id_profile_field
            type: integer
            id: true
    fields:
        value: 
            column: value
            type: string
            length: 255
    lifecycleCallbacks: {  }
