Odiseo\Bundle\UserBundle\Entity\UserWishlist:
    type: entity
    table: wishes
    repositoryClass: Odiseo\Bundle\UserBundle\Repository\UserWishlistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ownerId: 
            column: owner_id
            type: integer
        dateCreated:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
    oneToOne:
        wished:
             targetEntity: \Odiseo\Bundle\ProductBundle\Entity\Product
             joinColumn:
                   name: wished_id
                   referencedColumnName: id
    lifecycleCallbacks: {  }