Odiseo\Bundle\UserBundle\Entity\UserProfile:
    type: entity
    table: user_profile
    repositoryClass: Odiseo\Bundle\UserBundle\Repository\UserProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
                on: update  
        name:
            column: name
            type: string
            length: 255
        lastName:
            column: last_name
            type: string
            lenght: 255
        address:
            column: address
            type: string
            length: 255
        phone:
            column: phone
            type: string
            varchar: 255
    manyToOne:
        user:
            targetEntity: \Odiseo\Bundle\UserBundle\Entity\User
            inversedBy: profiles
            joinColumn:
                name: id_user
                referencedColumnName: id
                onUpdate: 'CASCADE'
        type:
            targetEntity: \Odiseo\Bundle\UserBundle\Entity\UserProfileType
            joinColumn:
                name: profile_type_id
                referencedColumnName: id
                onUpdate: 'CASCADE'
           
