Odiseo\Bundle\UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: Odiseo\Bundle\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
              timestampable:
               on: update
               
    oneToMany:
      profiles:
          targetEntity: \Odiseo\Bundle\UserBundle\Entity\UserProfile
          mappedBy: user
            
      products:
          targetEntity: \Odiseo\Bundle\ProductBundle\Entity\Product
          mappedBy: vendor
    
      orders:
          targetEntity: \Odiseo\Bundle\OrderBundle\Entity\Order
          mappedBy: buyer

