Odiseo\Bundle\UserBundle\Entity\UserProfileTypeField:
    type: entity
    table: profile_type_field
    repositoryClass: Odiseo\Bundle\UserBundle\Repository\UserProfileTypeFieldRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name: 
            column: name
            type: string
            length: 255
    manyToOne:
       profileType:
           targetEntity: \Odiseo\Bundle\UserBundle\Entity\UserProfileType
           inversedBy: fields
           joinColumn:
                name: id_profile_type
                referenceColumnName: id
                onUpdate: 'CASCADE'
    lifecycleCallbacks: {  }
