Odiseo\Bundle\ProductBundle\Entity\ProductTypeFieldValue:
    type: entity
    table: media_type_field_value
    repositoryClass: Odiseo\Bundle\ProductBundle\Repository\ProductTypeFieldValueRepository
    id:
        idProduct:
            column: id_media
            type: integer
            id: true
        idProductField:
            column: id_media_field
            type: integer
            id: true
    fields:
        value: 
            column: value
            type: string
            length: 255
    lifecycleCallbacks: {  }
