Odiseo\Bundle\ProductBundle\Entity\ProductType:
    type: entity
    table: media_type
    repositoryClass: Odiseo\Bundle\ProductBundle\Repository\ProductTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            column: description
            type: string
            length: 255
    oneToMany:
        fields:
          targetEntity: \Odiseo\Bundle\ProductBundle\Entity\ProductTypeField
          mappedBy: productType        
    lifecycleCallbacks: {  }
