Odiseo\Bundle\ProductBundle\Entity\ProductState:
    type: entity
    table: media_state
    repositoryClass: Odiseo\Bundle\ProductBundle\Repository\ProductStateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
           column: name
           type: string
           length: 255
    oneToOne:
         previousState:
            targetEntity: Odiseo\Bundle\ProductBundle\Entity\ProductState
            joinColumn:
                name: previous_state
                referencedColumnName: id
                onDelete: "CASCADE"
         nextState:
            targetEntity: Odiseo\Bundle\ProductBundle\Entity\ProductState
            joinColumn:
                name: next_state
                referencedColumnName: id
                onDelete: "CASCADE"
    lifecycleCallbacks: {  }
