Odiseo\Bundle\ProductBundle\Entity\ProductAsset:
    type: entity
    table: media_asset
    repositoryClass: Odiseo\Bundle\ProductBundle\Repository\ProductAssetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        path:
            column: path
            type: string
            length: 255
        position:
            column: position
            type: integer
            nullable: true
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            column: updated_at
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update    
    
    manyToOne:
      product:
           targetEntity: \Odiseo\Bundle\ProductBundle\Entity\Product
           inversedBy: assets
           joinColumn:
                name: id_product
                referenceColumnName: id
                onUpdate: 'CASCADE' 
    lifecycleCallbacks: {  }
