<?php

namespace Odiseo\Bundle\UserBundle\Repository;

/**
 * UserProfileTypeFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileTypeRepository extends \Doctrine\ORM\EntityRepository
{	
}