<?php

namespace Odiseo\Bundle\UserBundle\Repository;

/**
 * UserProfileFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileTypeFieldRepository extends \Doctrine\ORM\EntityRepository
{	
}