<?php

namespace Odiseo\Bundle\UserBundle\Repository;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends \Doctrine\ORM\EntityRepository
{	
}