odiseo_product_index:
    path:     /
    defaults: { _controller: "OdiseoProductBundle:Frontend/Product:index" }
    
odiseo_product_show:
    path:     /{id}
    defaults: { _controller: "OdiseoProductBundle:Frontend/Product:show" }
    requirements:
        id:  \d+
    
odiseo_product_new:
    path:     /new
    defaults: { _controller: "OdiseoProductBundle:Frontend/Product:new" }    

odiseo_product_do_filter:
    path:     /filter
    defaults: { _controller: "OdiseoProductBundle:Frontend/Product:doFilter" }
    
odiseo_product_filter_by_username:
    path:     /filter/by-username/{username}
    defaults: { _controller: "OdiseoProductBundle:Frontend/Product:searchProductsForUserName" }
    
odiseo_product_filter_by_key:
    path:     /filter/by-{key}/{value}
    defaults: { _controller: "OdiseoProductBundle:Frontend/Product:filter" }