Odiseo\Bundle\LokalBuddyBundle\Entity\Message:
    type: entity
    table: message
    repositoryClass: Odiseo\Bundle\LokalBuddyBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        dateCreated:
            column: created_at
            type: datetime
            gedmo:
              timestampable:
                on: create
        subject: 
            column: subject
            type: text
        body: 
            column: body
            type: text
        isReaded: 
            column: is_readed
            type: boolean
        isSent: 
            column: is_sent
            type: boolean
        isDeleted: 
            column: is_deleted
            type: boolean
    manyToOne:
        sender:
            targetEntity: \Odiseo\Bundle\UserBundle\Entity\User
            joinColumn:
                name: sender_id
                referencedColumnName: id
                onUpdate: 'CASCADE'
        receiver:
            targetEntity: \Odiseo\Bundle\UserBundle\Entity\User
            joinColumn:
                name: receiver_id
                referencedColumnName: id
                onUpdate: 'CASCADE'
        product:
             targetEntity: \Odiseo\Bundle\ProductBundle\Entity\Product
             joinColumn:
                   name: product_id
                   referencedColumnName: id
                   onUpdate: 'CASCADE'
    lifecycleCallbacks: {  }