Odiseo\Bundle\LokalBuddyBundle\Entity\Product:
    type: entity
    table: odiseo_product
    fields:        
        maxQuantity:
            column: max_quantity
            type: integer
            nullable: true